# cargo-deny is really only ever intended to run on the "normal" tier-1 targets
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
]

# Ignore dev dependencies as well as all dependencies of `test-helpers` since it is only a dev dependency for the other packages.
exclude-dev = true
exclude = ["cw-dex-test-helpers"]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"
unsound = "deny"
ignore = []

[bans]
multiple-versions = "allow"
deny = []
skip = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []
[sources.allow-org]
github = []

[licenses]
unlicensed = "deny"
copyleft = "deny"
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93
allow = ["Apache-2.0", "MIT", "BSD-3-Clause", "MPL-2.0"]
exceptions = [{ allow = ["Unicode-DFS-2016"], name = "unicode-ident" }]
