[package]
authors = ["Apollo Devs"]
description = "Helper library for interacting with Cosmos dexes"
edition = "2021"
license = "MPL-2.0"
name = "cw-dex"
repository = "https://github.com/apollodao/cw-dex"
version = "0.1.0"

[features]
default = []
osmosis = ["dep:osmosis-std"]
astroport = ["dep:astroport-types","dep:uint"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
thiserror = { workspace = true }
apollo-cw-asset = { workspace = true }
cw-utils = { workspace = true }
cw20 = { workspace = true }
apollo-utils = { workspace = true }

# Osmosis
osmosis-std = { workspace = true, optional = true }

# Astroport
astroport-types = { workspace = true, optional = true}
uint = {version = "0.9.3", optional = true}

[dev-dependencies]
osmosis-test-tube = { workspace = true }
cw-it = { workspace = true }
test-case = "2.2.2"
cw-dex-test-contract = { workspace = true }
cw-dex-test-helpers = { workspace = true }
proptest = "1.0.0"
cw20-base = { workspace = true }
