name: Linting and formatting
on:
  pull_request:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target branch'
        required: false
        default: 'develop'
        type: string

env:
  RUSTFLAGS: -D warnings

jobs:
  lint-and-format:
    name: Lint and format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: actions/checkout@v3

      - name: Checkout sources on workflow dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy

      - name: Install cargo-machete
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-machete

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: clippy
          args: --fix -- -D warnings

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: fmt
          args: --all -- --check

      - name: Run cargo machete
        uses: actions-rs/cargo@v1
        with:
          command: machete

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
