
name: Versioning
on:
  pull_request:
    branches:
      - master
      - ci/semver-concom-automation
  workflow_dispatch:
    logLevel:
      inputs:
        description: 'Log level'
        required: false
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  semver-determine:
    name: Determine next version number
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Determine version number
        id: semver
        uses: grumpy-programmer/conventional-commits-semver-release@v1
        with:
          token: ${{ secrets.APOLLO_CI_PAT }}
          branch: master
          majorList: feat!, feature! fix!, bugfix!, perf!, refactor!, chore!
          minorList: feat, feature
          patchList: fix, bugfix, perf, refactor, test, tests, chore

      - name: Update Cargo.toml
        id: update
        uses: ciiiii/toml-editor@1.0.0
        with:
          file: "Cargo.toml"
          key: "package.version"
          value: "${{ steps.semver.outputs.nextStrict }}"

      - name: Commit changes and push
        id: push-commit
        uses: swinton/commit@v2.x
        env:
          GH_TOKEN: ${{ secrets.APOLLO_CI_PAT }}
        with:
          files: |
            Cargo.toml
          commit-message: Update Cargo.toml version from ${{ steps.semver.outputs.current }} to ${{ steps.semver.outputs.next }}


