
name: Versioning
on:
  pull_request:
    branches:
      - master
      - ci/semver-concom-automation
  workflow_dispatch:
    logLevel:
      inputs:
        description: 'Log level'
        required: false
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  semver-determine:
    name: Determine next version number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Determine version number
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: master
          majorList: feat!, feature! fix!, bugfix!, perf!, refactor!, chore!
          minorList: feat, feature
          patchList: fix, bugfix, perf, refactor, test, tests, chore

      - name: Update Cargo.toml
        id: update
        uses: ciiiii/toml-editor@1.0.0
        with:
          file: "Cargo.toml"
          key: "package.version"
          value: "${{ steps.semver.outputs.nextStrict }}"

      - name: Commit changes, tag and push
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: 'Cargo.toml'
          tag: '${{ steps.semver.outputs.next }}'
          message: Update Cargo.toml version from ${{ steps.semver.outputs.current }} to ${{ steps.semver.outputs.next }}
